services:
  # Serviço da Aplicação (Back-end)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Diz ao Docker para usar o estágio "development" do Dockerfile
    container_name: intro_clean_app
    command: npm run dev # Comando para rodar em modo de desenvolvimento
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src # Sincroniza sua pasta 'src' local com a do container
    environment:
      # Passa as variáveis do seu arquivo .env para dentro do container
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - clean_network

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres
    container_name: pg_clean_arch_dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - clean_network

# Define a rede que os containers usarão para se comunicar
networks:
  clean_network:
    driver: bridge