services:
  # 1. O Banco de Dados de Teste
  db_test:
    image: postgres
    container_name: pg_clean_arch_test
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cleandb_test
    ports:
      - '5434:5432'
    
    # 2. O Healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d cleandb_test"] # Comando que verifica se o Postgres está pronto
      interval: 5s   # Tenta a cada 5s
      timeout: 5s    # Espera no máximo 5s
      retries: 5     # Tenta 5 vezes antes de falhar
    networks:
      - test_network

  # 3. O Serviço "Tester" que roda os testes
  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Usa o 'stage' de dev (com 'npm install')
    command: npm run test:integration
    environment:
      NODE_ENV: test
      DB_HOST: db_test
      DB_PORT: 5432
      DB_USER: docker
      DB_PASS: docker
      DB_NAME: cleandb_test
      JWT_SECRET: test_secret
    
    depends_on:
      db_test:
        condition: service_healthy # Espera o 'healthcheck' do 'db_test' passar
    networks:
      - test_network

networks:
  test_network:
    driver: bridge